network:  
  version: 2
  ethernets:
    eth0:
      addresses:
        - 192.168.1.200/24
      gateway4: 192.168.1.254
      nameservers:
        addresses:
          - 8.8.8.8
      dhcp4: false  # Disable DHCP since we are using static IPs
      critical: true
